#!/usr/bin/env bash
# cleanup_flatpak.sh - Remove every artefact build_flatpak.sh produces.
#
# Scoped to the Flatpak build ALONE.  The Nuitka executable (buildexe.py) and
# the Windows installer (buildinstaller.py) write elsewhere and are deliberately
# left untouched, so the three delivery paths stay independent and cleaning one
# never costs another a rebuild.
#
# Usage:
#   ./cleanup_flatpak.sh            - remove build artefacts, keep the app installed
#   ./cleanup_flatpak.sh --uninstall - also uninstall the locally installed Flatpak

set -euo pipefail

APP_ID="uk.co.oernster.o7Debrief"
BUNDLE="o7debrief.flatpak"
MANIFEST="${APP_ID}.yml"

UNINSTALL=0
for arg in "$@"; do [[ "$arg" == "--uninstall" ]] && UNINSTALL=1; done

echo "Cleaning Flatpak build artefacts..."

# Generated by build_flatpak.sh: the builder trees, the local repo, the
# pre-downloaded wheels, the self-generated manifest and the packaging helpers
# (launcher, desktop entry, metainfo and the derived icon set).  None is
# committed, so removing them loses nothing that is not regenerated.
rm -rf .flatpak-build .flatpak-repo .flatpak-builder .flatpak-wheels
rm -rf packaging
rm -f "${MANIFEST}"
rm -f "${BUNDLE}"

echo "  Removed build trees, wheels, manifest, packaging helpers and bundle."

if [[ $UNINSTALL -eq 1 ]]; then
    echo "Uninstalling ${APP_ID}..."
    flatpak uninstall --user --noninteractive "${APP_ID}" || true
    echo "  Uninstalled."
    echo
    echo "Note: the start-on-sign-in entry is written OUTSIDE the sandbox, at"
    echo "  \${XDG_CONFIG_HOME:-\$HOME/.config}/autostart/${APP_ID}.desktop"
    echo "Uninstalling the app does not remove it, so a stale entry would try to"
    echo "run an app that is no longer installed.  Remove it with:"
    echo "  rm -f \"\${XDG_CONFIG_HOME:-\$HOME/.config}/autostart/${APP_ID}.desktop\""
fi

echo "Done."
